### ISSUE TITLE
Electron app not found in GNOME applications menu after installation

### ISSUE THREAD

**Issue by anto-christo** [electron-userland/electron-installer-debian#168] opened 2018-12-31 13:51 UTC
OS: Ubuntu 18
electron: 3.0.10
electron-forge: 5.2.3
electron-prebuilt-compile: 3.0.13

I ran the `electron-forge make` command.
All the operations were completed successfully and the output folder was generated with a .deb file and some other files.

I ran the .deb file and the application got installed successfully but I'm not able to find the application installed anywhere in my system. It's not there in the Applications menu.

However, under the 'installed' section in Ubuntu Software Center, the app is listed under the 'Add-ons' subsection. (frappe-accounting is the name of my app)
![addon](https://user-images.githubusercontent.com/22641196/50561460-0a5df880-0d31-11e9-909e-e10488d0068e.png)

- package.json
```js
{
  "name": "frappe-accounting",
  "description": "Simple Accounting app for everyone",
  "productName": "Frappe-Accounting",
  "version": "0.0.2",
  "author": {
    "name": "Frappe Technologies Pvt. Ltd.",
    "email": "hello@frappe.io"
  },
  "config": {
    "forge": {
      "make_targets": {
        "linux": [
          "deb"
        ]
      },
      "electronPackagerConfig": {},
      "electronWinstallerConfig": {
        "name": ""
      },
      "electronInstallerDebian": {},
      "electronInstallerRedhat": {},
      "github_repository": {
        "owner": "",
        "name": ""
      },
      "windowsStoreConfig": {
        "packageName": ""
      }
    }
  },
  "main": "dist/electron/main.js",
  "license": "MIT",
  "scripts": {
    "test": "mocha tests",
    "start": "frappe start",
    "electron": "cross-env ELECTRON=true frappe start electron",
    "postinstall": "electron-builder install-app-deps",
    "dist": "electron-builder"
  },
  "dependencies": {
    "frappejs": "github:frappe/frappejs",
    "popper.js": "^1.14.4",
    "vue-color": "^2.7.0",
    "vue-toasted": "^1.1.25"
  },
  "devDependencies": {
    "electron-prebuilt-compile": "3.0.13"
  }
}

```

Any help is appreciated. Thank you.

**Comment by malept** [comment] 2019-01-01 21:30
Moved issue to `electron-installer-debian`.

*Note: [Forge 5.x currently uses `^1.0.0`](https://github.com/electron-userland/electron-forge/blob/8b290d63a811101d474ced4a6982f3626f507a35/package.json#L157)*.

**Comment by fcastilloec** [comment] 2019-01-01 22:43
It might be related to this old issue #107 
I don't use `electron-forge` so I'm not 100% familiar with what's going on there. Usually the problems I've encounter is because `electron-packager` uses the `productName`, you can read the full answer in this comment https://github.com/electron-userland/electron-installer-debian/issues/107#issuecomment-334215509
@anto-christo Can you post the contents of your `.desktop` file? or if you feel comfortable sharing, the `.deb` created by forge.

**Comment by malept** [comment] 2019-01-01 23:05
Forge more or less forwards user config to `electron-installer-debian` (except for `arch`, `src`, `dest`, and `rename`).

**Comment by fcastilloec** [comment] 2019-01-01 23:13
@malept is `appname` used when packaging the app with `electron-packager`? in other words, when the user doesn't provide any configurations, and forge uses its defaults, does it take care of the problem `electron-packager` introduces?

**Comment by malept** [comment] 2019-01-01 23:21
`appname` is a concept for the `electron-packager` CLI only. Forge uses the API, so Forge users must set the app name either in `package.json`'s `name` or `productName` fields.

**Comment by fcastilloec** [comment] 2019-01-01 23:36
The problem is with `appname` when running from the CLI, but if it's used programmatically then the problem is with the `name` option. Here's the same description as listed in the previously mentioned issue, but from their [programatically API](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#name)
When forge users have a `name` and `productName` in their `package.json`, `electron-packager` will use first the `productName` and if not found the `name`. I'm guessing that for @anto-christo the product name had spaces (i.e. Frappe Accounting), this is not a valid name for Linux.
If you specify the `options.name` for `electron-packager` to be the same as what you have under your `package.json` `name` field, this should be fixed.

I think this is a bug with forge and not this module. Forge should deal with the fact that `electron-packager` uses the wrong field (`productName`) from a Linux point of view, or at least warn the user about this.
A lot of people might not see this problem because their `name` and `productName` are the same.

**Comment by tymmesyde** [comment] 2019-01-02 08:33
Fixed for me, just specify the correct path of the binary in `options.bin`
Checked with `ls -la /usr/bin/dsound-player`

**Comment by fcastilloec** [comment] 2019-01-02 09:19
@malept I'm sorry but I confused the options. Users (and `electron-forge`) should use the `executableName` option with `electron-packager`, either in the CLI or programatically.
I remember that around a year ago (https://github.com/electron-userland/electron-packager/commit/64caae7d5ab6a73e83ab6e3856cb370936fd57be), that option was introduced into `electron-packager` just so we could address this issues of wrong symlinks and wrong executable names.
Rather than using `options.bin` with this module, use `executableName` with `electron-packager`. This way `electron-packager` will produce a valid executable name following Linux naming conventions.

As an example, using @anto-christo `package.json`. If we decide to use `options.bin` and leave `electron-packager` with its defaults, the executable will be created as `Frappe-Accounting` which then is  used in `options.bin`, but this doesn't follow Linux naming conventions.
If we use `executableName` instead and set it as `frappe-accounting`, then there's no need to set any options in this module, and we've followed naming conventions in Linux.

**Closed** 2019-01-02 17:24 UTC
