### ISSUE TITLE
Error: could not find the Electron app binary at "dist/app-linux-x64/lumzapp-electron". You may need to re-bundle the app using Electron Packager's "executableName" option

### ISSUE THREAD

**Issue by heyimgab** [electron-userland/electron-installer-debian#252] opened 2021-06-03 08:24 UTC
Error: could not find the Electron app binary at "dist/app-linux-x64/lumzapp-electron". You may need to re-bundle the app using Electron Packager's "executableName" option

**Comment by malept** [comment] 2021-06-03 14:11
Duplicate of #198

**Closed by malept** 2021-06-03 14:11 UTC

**Comment by cjm-korea** [comment] 2023-05-04 07:48
I also experienced this error. I posted how to fix the error after a lot of trial and error.

https://it-jm.tistory.com/187
