### ISSUE TITLE
Hello, I had some problems packaging my application with electronic-installer-debian

### ISSUE THREAD

**Issue by 1006569910** [electron-userland/electron-installer-debian#227] opened 2020-05-08 09:49 UTC
![1588931179(1)](https://user-images.githubusercontent.com/41898623/81394250-3cb50c80-9154-11ea-92d9-e36af7e9e752.png)

**Comment by fcastilloec** [comment] 2020-05-08 17:00
duplicate of  #175 and #118

**Closed by fcastilloec** 2020-05-08 17:00 UTC
Labels: duplicate
